"""Human-authored scenario catalog for the SLM SFT candidate corpus.

Each string is a distinct task, not a filled copy of a benchmark template.
Split-specific renderers in build_manifest.py add modest format diversity; the
scenario text remains the source of the substantive task and constraints.
"""


TRAINING = {
    "general_chat_writing": [
        "Rewrite a note to the Harbor Lane bakery supplier: Tuesday's flour delivery must move to Thursday morning because the freight elevator is being inspected. Keep it warm, take responsibility for the late notice, and ask for confirmation in at most 90 words.",
        "Turn these observations from a community-garden workday into a four-bullet recap: 27 volunteers attended; six beds were mulched; the west tap leaks; seedlings need labels; the next workday is May 18. Put the urgent maintenance item first.",
        "Draft a tactful reply to a friend who repeatedly arrives late. State that you value the friendship, explain the effect on shared plans, and propose one concrete arrangement without sounding accusatory.",
        "Create a compact FAQ entry for the Northpoint Library makerspace explaining that orientation is free, laser-cutter booking opens seven days ahead, users must bring approved materials, and staff do not design projects for patrons.",
        "Mina wants a quiet Saturday walk under five miles, dislikes steep climbs, and needs a cafe nearby. Compare Cedar Marsh Loop (4.2 miles, flat, cafe 0.3 miles away) with Eagle Bluff Path (3.1 miles, 900-foot climb, no cafe) and recommend one in three sentences.",
        "Write an apology to a customer whose blue serving bowl arrived twelve days late after a kiln failure. Offer either free express shipping when it is ready or an immediate refund, and avoid blaming the courier.",
        "Build a 35-minute agenda for the first meeting of a neighborhood compost group. It must cover roles, acceptable materials, bin location, pest prevention, and one clearly assigned next action.",
        "Convert these rough notes into a six-step guest check-in procedure for community radio: verify release; check pronunciation; silence phone; set microphone distance; record ten-second level test; point out the stop signal.",
        "Improve this museum audio-guide opening while preserving its facts: 'This room has old maps. People made them before satellites. Some are wrong but they helped sailors.' Make it vivid but not grandiose, in 55-75 words.",
        "Respond supportively to a roommate who says, 'I feel as if I do all the cleaning.' Acknowledge the concern, avoid admitting facts you do not know, and suggest a low-friction way to divide chores.",
        "Summarize these cafe comment-card themes for the owner: praise for staff friendliness (18 cards), complaints about lunchtime noise (11), requests for oat milk (7), and two reports of a loose table near the window. Separate safety from preference.",
        "Write a welcoming message for new members of the Briar Chess Club. Mention Wednesday meetings at 6:30, that all skill levels are welcome, and that loaner sets are available. End with one easy question that invites a reply.",
        "Explain to a nontechnical neighbor how to restart a home router safely. Distinguish restarting from factory-resetting, give no more than five steps, and say when to contact the internet provider.",
        "Suggest five names for a refill shop that sells soap and pantry staples in a lakeside town. For each name, add a six-word-or-shorter rationale; avoid puns involving waste or trash.",
        "Explain the phrase 'the last straw' to a curious nine-year-old using a new example about sharing art supplies. Do not repeat the traditional camel story.",
        "Plan a two-hour birthday outing for six adults near Alder Square with a $120 total budget: picnic snacks cost $42, mini golf costs $11 each, and the public conservatory is free. Include a rainy-day revision after the initial plan.",
    ],
    "code_agent_tools": [
        "Write a Python function `merge_counts(left, right)` that returns a new dictionary containing the sum for shared string keys. Inputs must not be mutated. Include type hints and three assert examples, including an empty input.",
        "Given tables `orders(id, customer_id, total, created_at)` and `customers(id, region)`, write PostgreSQL that returns each region's 2025 order count and revenue, including regions with zero orders. Explain the placement of the date filter.",
        "Find and fix the JavaScript bug in `const doubled = values.map(v => { v * 2 });`. Return the corrected line and a one-sentence explanation; do not rewrite it as a loop.",
        "Provide a regular expression for whole inventory codes shaped like two uppercase letters, a hyphen, and exactly four digits. Show two matches and two nonmatches, and state whether anchors are required.",
        "An agent can call `lookup_order(order_id)` or `search_orders(email, since_date)`. The user says, 'Where is my order? I bought it as samira@pond.example last Friday but lost the number.' Choose the first tool call and provide valid JSON arguments using date 2026-06-12 as last Friday.",
        "Design a JSON response for a successful `POST /v1/reservations` call. It needs an immutable reservation ID, ISO-8601 creation time, status, party size, and links for self and cancellation. Provide only valid JSON with plausible values.",
        "Give a safe Git command sequence to move the uncommitted changes in `notes.md` onto a new branch named `docs/field-notes`, preserving all other uncommitted files. Explain any limitation in two short bullets.",
        "Write a POSIX shell one-liner that lists regular `.log` files directly inside `/var/tmp/harbor`, newest first, without descending into subdirectories. Make it safe for spaces in filenames.",
        "Write Python using the standard `csv` module to read `meters.csv` with columns `site,kwh` and print total kWh per site in alphabetical order. Malformed numeric rows should be reported to stderr and skipped.",
        "Create five pytest test cases, expressed as code, for `slugify(text)` where spaces become hyphens, repeated separators collapse, Unicode letters are preserved, and leading or trailing separators disappear.",
        "Review this function for one correctness issue and one interface issue: `def first_even(xs): return next(x for x in xs if x % 2 == 0)`. Then supply a revised version whose missing-value behavior is explicit.",
        "You have tools `read_file(path)` and `write_file(path, content)`. A user asks to change `theme = 'day'` to `'night'` in `prefs.py` without altering anything else. State the first tool call only, in compact JSON.",
        "Implement `chunked(items, size)` as a lazy Python generator. Reject booleans and nonpositive sizes with `ValueError`, work with any iterable, and avoid importing third-party packages.",
        "Translate this curl request into Python `urllib.request` code: POST JSON `{'enabled': true}` to `https://api.example.test/flags/7` with bearer token stored in `TOKEN`. Include a 10-second timeout and error handling that does not print the token.",
        "A SQLite query `SELECT category, name, MAX(price) FROM products GROUP BY category` returns arbitrary names on ties. Rewrite it with a window function so every category yields exactly one row, breaking ties by lexicographically smallest name.",
        "A deployment agent receives: build `b-184` passed; staging health is green; production approval is absent. Its actions are `deploy_staging`, `request_approval`, and `deploy_production`. Return a two-step action plan that respects the approval gate.",
    ],
    "math_quantitative": [
        "A food co-op buys 18 cases with 24 jars each. Seven jars break and the rest are packed equally into five displays, with leftovers stored. How many jars go in each display and how many are left? Show compact arithmetic.",
        "A fair six-sided die is rolled twice. What is the probability that the sum is at least 10? Give the reduced fraction and briefly enumerate the favorable outcomes.",
        "Solve `3(2x - 5) + 4 = 5x + 9`, then verify the value by substituting it into both sides.",
        "A rectangular rain garden is 7.5 m by 4 m. A 0.5 m-wide path runs inside all four edges. Find the planted area, stating the dimensions of the inner rectangle.",
        "A ferry travels 36 km downstream in 1.5 hours and returns upstream in 2.25 hours. Assuming constant current and still-water speeds, find both speeds in km/h.",
        "The values are 12, 15, 15, 18, and 25. Compute the mean, median, population range, and identify which measure changes most if 25 is replaced by 60.",
        "Convert 2.75 US gallons to liters using 1 gallon = 3.78541 liters. Round only the final answer to two decimal places.",
        "A savings account starts with $1,200 and earns 4% annually, compounded once per year. What is the balance after three years? Show the recurrence and round to cents.",
        "A map uses scale 1:25,000. Two trailheads are 7.2 cm apart on the map. Find the real distance in kilometers and explain the unit conversions.",
        "A recipe for eight servings uses 300 g of rice and 450 mL of broth. Scale it to 14 servings, and report both amounts without rounding.",
        "A line passes through (-2, 5) and (4, -1). Find its slope and equation in slope-intercept form, then check one point.",
        "A shop marks a jacket down 20% from $85, then applies 7.5% sales tax. Calculate the final price and explain why adding the percentages would be wrong.",
        "Four machines finish a batch in 15 hours at equal constant rates. After five hours, one machine stops. How many additional hours do the remaining machines need? State the work-rate model.",
        "A survey has 42 yes, 28 no, and 10 undecided responses. Give each percentage and a 95% confidence interval for the yes proportion using the normal approximation; note one limitation.",
        "Find the smallest positive integer that leaves remainder 2 when divided by 5 and remainder 4 when divided by 7. Demonstrate the check.",
        "A spreadsheet has quantity in B2, unit price in C2, and discount rate in D2. Give an Excel formula for the discounted line total that treats a blank discount as zero and can be filled downward.",
    ],
    "science_technical": [
        "Explain why leaves usually look green and why many turn red or yellow in autumn. Separate what happens to chlorophyll from where the other colors come from, in language suitable for middle school.",
        "A cyclist and bicycle have combined mass 82 kg and accelerate from rest to 6 m/s in 4 seconds. Ignoring resistance, compute average net force and kinetic energy at 6 m/s, with units.",
        "Describe what happens at the particle level when table salt dissolves in water. Use the terms ion, polarity, and hydration shell accurately without claiming the salt molecules simply disappear.",
        "Explain how an oceanic plate can cause a volcanic arc when it meets a continental plate. Give the causal chain in five numbered steps.",
        "Compare a refracting telescope and a reflecting telescope on how they focus light, one common optical limitation, and why large research telescopes usually use mirrors.",
        "Design a classroom experiment testing how water temperature affects the time a sugar cube takes to dissolve. Name the independent variable, dependent variable, three controls, and a repeat strategy.",
        "A steel bridge deck is 180 m long at 10°C. Using linear expansion coefficient 12×10^-6 per °C, estimate its length change at 35°C and state an engineering implication.",
        "Explain why antibiotics do not treat influenza and how unnecessary antibiotic use can increase resistant bacterial infections. Avoid implying that a person's body becomes resistant.",
        "Contrast weather and climate using one example of each, then explain why a single cold day does not disprove long-term warming.",
        "Describe how a lithium-ion battery moves lithium ions and electrons during discharge. Mention anode, cathode, electrolyte, and external circuit; do not give construction instructions.",
        "A pond sample contains abundant algae, low dissolved oxygen before dawn, and elevated nitrate after fertilizer runoff. Propose the most likely process and explain the oxygen pattern.",
        "Explain the difference between mass and weight to a student who says a 2 kg object 'weighs 2 kg.' Include its approximate weight on Earth using g = 9.8 m/s².",
        "Outline how polymerase chain reaction amplifies a chosen DNA region. Name the roles of primers, polymerase, nucleotides, and the three temperature stages without giving laboratory quantities.",
        "A sensor reports 10.02, 10.01, 10.03, and 10.02 V while a calibrated reference is 10.20 V. Distinguish precision from accuracy using these readings and suggest one calibration check.",
        "Explain why seasons are caused mainly by Earth's axial tilt rather than its distance from the Sun. Use the Northern and Southern Hemispheres as evidence.",
        "Compare series and parallel household circuits in terms of voltage, current paths, and what happens when one lamp fails. Keep the explanation conceptual and safety-conscious.",
    ],
}


OVERLAPPING_TEST = {
    "general_chat_writing": [
        "Condense this notice for a bicycle-room door: the lock will be replaced July 8 between 9 and 11 a.m.; bicycles can remain inside; residents must collect a new key from the front desk after noon; identification is required. Use a heading and at most 45 words.",
        "Write a calm message declining a second volunteer shift at the Willow Street food pantry this month. Express appreciation, mention an existing commitment without inventing details, and offer to share the signup link.",
        "Organize these notes into a decision memo: the rooftop movie costs $680 and seats 90; the indoor screening costs $430 and seats 55; rain chance is 40%; 62 people registered. Include recommendation, rationale, and contingency.",
        "Edit this sentence for clarity without changing its meaning: 'After reviewing it with Priya, the revised schedule was sent by Luis to the whole team because she thought the dates in it were confusing.' Explain what ambiguity remains if no facts are added.",
        "Create three subject-line options and a 70-word email asking members of the Elm Choir to return borrowed folders by August 3. The tone should be friendly but make the deadline unmistakable.",
        "A visitor asks whether the Riverside archive is accessible. Reply using only these facts: ramp at east entrance; lift to all public floors; one wheelchair available first-come; quiet room on floor two; service animals welcome; accessibility desk reachable by text.",
        "Turn a rambling voice memo into a checklist: reserve eight folding tables, confirm electricity at the pavilion, buy compostable cups, ask Noor about the permit, and cancel the backup tent if Friday's forecast is dry.",
        "Draft a neutral introduction for a survey about changes to bus stop locations. Make clear that the proposal is not final, responses close October 2, and demographic questions are optional.",
        "Explain the difference between proofreading and substantive editing to a first-time author. Use one original sentence to demonstrate both kinds of change.",
        "Write a brief thank-you note to the anonymous person who returned a lost sketchbook to the Juniper Cafe. Avoid guessing how or where it was found and mention why the drawings matter.",
        "Compare two rehearsal spaces for a five-person band: Foundry Room is $28/hour with drums but closes at 8; Loft Nine is $22/hour without drums and closes at 11. Rehearsal is 7:30-9:30 and renting drums costs $18. Recommend with total cost.",
        "Make a seven-item packing list for an overnight train trip with a work presentation the next morning. Separate essential presentation items from comfort items and avoid brand recommendations.",
        "Rewrite a blunt comment—'This proposal is vague and nobody knows who is doing what'—as specific, constructive feedback that asks for owners, dates, and acceptance criteria.",
        "Prepare a 20-minute facilitation plan for choosing among three mural sketches. It must prevent the artists from voting on their own work and give quieter participants a way to contribute.",
        "Summarize for a parent: robotics club meets twice monthly; students work in pairs; no prior coding is needed; safety glasses are supplied; missed sessions cannot be made up. Use two short paragraphs, not bullets.",
        "Invent four non-rhyming names for a mobile repair cafe that visits rural towns. Each name should sound trustworthy and work without the word 'fix.' Select the strongest and justify it.",
        "Write an out-of-office reply covering September 14-18. Direct urgent building issues to facilities@example.test and all other requests to the shared queue; do not promise a response date.",
        "A colleague says your presentation moved too quickly. Draft a response that thanks them, asks one diagnostic question, and commits to one concrete improvement for the next session.",
        "Turn these event rules into welcoming prose: doors 6:00; talk 6:30; late seating only at pause; water allowed; photography prohibited; captions available; leave aisle seats for mobility needs.",
        "Explain to a new apartment tenant why pouring cooking grease down the sink causes problems and give two practical disposal options. Keep it under 100 words and do not overstate environmental claims.",
        "Create a three-day watering handoff for twelve office plants. Kai covers Monday, Jo covers Tuesday, and Bea covers Wednesday; succulents are skipped; the fern gets half a cup daily; all others get a quarter cup once.",
        "Write a tactful correction for a newsletter that listed the poetry reading as Friday when it is Thursday, November 6. State that the venue and 7 p.m. time are unchanged and apologize once.",
        "Synthesize opposing feedback on a park bench: older residents want armrests for standing support; some sleepers say dividers are hostile; maintenance wants replaceable parts. Frame the tradeoff and propose a next research step without choosing a design.",
        "A ten-year-old asks why adults say 'read the room.' Explain the expression with a scenario at a quiet school assembly and one counterexample where speaking up is important.",
        "Draft an invitation to a skill-sharing evening where attendees may teach a five-minute everyday skill. Include two example skills, accessibility contact details, and an opt-in rather than pressuring language.",
        "Rewrite this product description to remove unsupported claims: 'Our revolutionary bamboo towel eliminates germs, saves the planet, and stays soft forever.' Preserve only that it is made from 70% bamboo-derived viscose and 30% cotton.",
        "Give a four-part outline for a short oral history interview with a retired ferry captain. Include consent before recording and avoid leading questions about dangerous storms.",
        "Respond to a customer who received two identical invoices but may have been charged only once. Acknowledge the concern, request the invoice numbers, and explain how to verify the card statement without asserting billing status.",
        "Create a concise room-use policy from these constraints: bookings max two hours; leave ten minutes for cleanup; food only in sealed containers; minors need an adult; cancellations free until 24 hours before.",
        "Suggest a fair way for four housemates to choose bedrooms of unequal size when rent shares can differ. Give two methods, one using bidding and one using rotation, with a drawback of each.",
        "Write alt text, no more than 45 words, for an illustration showing three people planting reeds along an urban canal while a heron stands on a concrete wall. Describe relevant visual content without interpreting anyone's emotions.",
        "After proposing a quiet indoor book-swap for Sunday, revise the plan in response to: 'Two guests use wheelchairs, one is hard of hearing, and the elevator is out.' Explain whether to relocate or postpone, using only those facts.",
    ],
    "code_agent_tools": [
        "Implement a TypeScript function `uniqueBy<T, K>(items, keyFn)` that keeps the first item for each key while preserving order. Include the signature, implementation, and a short example with duplicate user IDs.",
        "Write a parameterized PostgreSQL query that finds available meeting rooms with capacity at least `$1` that have no booking overlapping `[$2, $3)`. Tables are `rooms(id, capacity)` and `bookings(room_id, starts_at, ends_at)`.",
        "Diagnose why `['10', '10', '10'].map(parseInt)` produces unexpected values in JavaScript. Give the correct expression and explain the callback-argument mismatch.",
        "Create a Python regular expression that captures a four-digit year and two-digit month from strings exactly shaped `report_YYYY-MM.csv`. Reject invalid months without attempting full calendar validation.",
        "Available tools are `get_weather(city, date)` and `find_station(city)`. A user asks whether to carry an umbrella in Porto tomorrow. Today is 2026-11-04. Return the necessary first call as JSON and do not call the station tool.",
        "Define a compact JSON Schema for an object with required `sku`, nonnegative integer `quantity`, and optional array `tags` containing unique nonempty strings. Disallow unknown top-level properties.",
        "Explain a non-destructive Git procedure for splitting the last local commit into two commits when it has not been pushed. Use commands, but include a checkpoint that preserves the current tree before recommitting.",
        "Write a Bash script fragment that reads newline-delimited filenames from stdin and prints SHA-256 plus filename using NUL-safe handling. State one limitation if filenames themselves arrive newline-delimited.",
        "Using only Python's standard library, parse an ISO-8601 UTC timestamp ending in `Z`, add 90 minutes, and emit a `Z` timestamp. Show behavior for `2026-12-31T23:15:00Z`.",
        "Write unittest cases for a `retry(operation, attempts)` helper: success first try, success after two failures, exhausted retries, and invalid zero attempts. Use a mock to verify call counts.",
        "Review `def average(xs): return sum(xs) / len(xs)` for empty input, iterator support, and numeric type behavior. Provide one revised implementation and document its chosen contract.",
        "A file-editing agent can `read(path)`, `replace(path, old, new)`, and `run_tests(target)`. The request is to rename `timeout_ms` to `request_timeout_ms` in `client.py` and its tests. Give the ordered calls, leaving arguments symbolic where contents must first be inspected.",
        "Write a pure Python `flatten_once(values)` that flattens lists and tuples one level but treats strings and dictionaries as atomic. Include four examples that expose the boundary.",
        "Convert an HTTPie command that sends form fields `title=Driftwood` and `year:=2024` to equivalent curl syntax. Preserve the distinction between text and numeric JSON values by choosing the correct content type.",
        "In SQL, return the second-highest distinct salary per department from `employees(department_id, salary)`, including no row for departments with fewer than two distinct salaries. Use `DENSE_RANK` and explain one line.",
        "A release agent sees version `2.4.0`, changelog updated, unit tests green, integration tests red, and a signed tag absent. From actions `rerun_integration`, `create_tag`, and `publish`, choose the only safe next action and justify it.",
        "Implement `debounce(fn, delay)` in browser JavaScript so the returned function preserves `this`, forwards arguments, and exposes a `cancel()` method. Provide concise code.",
        "Write a Rust function that returns the first word of a UTF-8 string slice using Unicode whitespace, without allocating. Include its lifetime-correct signature.",
        "A Python loop appends lambdas with `for i in range(3): funcs.append(lambda: i)`. Explain the late-binding result and show two different fixes, one using a default argument.",
        "Create a jq filter that converts `[{'name':'Ada','active':true},{'name':'Bo','active':false}]` into an object mapping only active names to `true`. Use valid jq syntax, correcting the single-quoted pseudo-JSON in your demonstration input.",
        "Write a minimal `.gitignore` rule set that ignores every `build` directory at any depth but keeps `docs/build/index.html` tracked. Explain the order of negation rules.",
        "Given a REST endpoint that may return 429 with `Retry-After`, sketch Python pseudocode for bounded retries with jitter. Do not retry other 4xx responses and cap total attempts at four.",
        "Implement binary search over a sorted list in Python, returning the leftmost index of a target or `-1`. Include invariants in comments and test duplicates.",
        "A calendar agent has `list_events(start,end)` and `create_event(title,start,end)`. The user asks to schedule a 30-minute review sometime Tuesday afternoon. State why the first call must be a listing and provide its arguments for 2026-08-11 12:00-17:00 with timezone America/Chicago.",
        "Write a secure SQL update in Python DB-API style that changes a user's display name by integer ID. Show transaction handling and parameter binding; do not interpolate either value.",
        "Explain the race in `if not path.exists(): path.write_text(data)` when two processes run it. Give an atomic creation alternative in Python and state what exception signals the loser.",
        "Create a small CSS grid with cards at least 14rem wide that wrap automatically. Use one declaration block and explain `minmax` in one sentence.",
        "Write a Python function to stream the ten largest numbers from an arbitrary iterable using O(10) memory. Handle fewer than ten inputs and return descending order.",
        "Given log lines `level=INFO msg='started'` and `level=ERROR msg='disk full'`, write an awk command that prints only ERROR lines. Then explain why this simple approach is unsuitable if field order or quoting varies.",
        "An agent receives a tool result `{'matches': [], 'query': 'invoice 4821'}` after calling search. Draft its next user-facing message: do not fabricate a result, mention the exact query, and ask for one useful alternative identifier.",
        "Refactor `try: return cache[k] except: return compute(k)` to catch only a missing key while preserving unrelated exceptions. Discuss whether the computed value should be inserted, but do not assume it.",
        "Specify property-based test ideas for a URL path joiner. Cover leading slashes, empty components, percent-encoded slashes, and the invariant that joining must not silently change query text.",
    ],
    "math_quantitative": [
        "A theatre sold 135 adult tickets at $14 and 86 student tickets at $9. Refunds were issued for four adult and three student tickets. Compute net ticket revenue with a clear expression.",
        "Two cards are drawn without replacement from a standard 52-card deck. Find the probability both are hearts, as a reduced fraction and decimal to four places.",
        "Solve the system `2x + y = 11` and `x - 3y = -9` by elimination, then check both equations.",
        "A circular fountain has radius 3.6 m and is surrounded by a 1.2 m-wide stone ring. Find the ring's area in terms of π and approximately to one decimal square meter.",
        "Train A leaves at 09:20 traveling 72 km/h. Train B follows the same route at 10:05 traveling 96 km/h. At what clock time does B catch A, assuming uninterrupted travel?",
        "For the data 4, 7, 7, 9, 10, 13, compute the sample standard deviation to three decimals and show the squared-deviation sum.",
        "A medication label is an educational arithmetic example: concentration 25 mg per 5 mL and an already-prescribed amount of 60 mg. Calculate the corresponding volume; do not give dosing advice.",
        "An investment loses 12% in year one and gains 12% in year two. Starting from $2,500, find the final value and explain why it does not return to $2,500.",
        "On a coordinate grid, rotate point (5, -2) 90 degrees counterclockwise about (-1, 3). Show translation, rotation, and translation back.",
        "Flour, sugar, and butter are mixed in ratio 5:2:3. If the mixture weighs 1.8 kg, find each mass in grams.",
        "Find the equation of the circle with center (2, -4) passing through (5, 0), and verify the radius using distance.",
        "A $160 appliance has successive discounts of 15% and $20, followed by 6% tax. Determine the final price and preserve the operation order.",
        "Pipe A fills a tank in six hours and pipe B fills it in nine hours. A drain empties it in 18 hours. How long with all three open? Use signed rates.",
        "A random sample of 120 packages has mean mass 502 g and sample standard deviation 8 g. Construct a 95% normal-approximation interval for the population mean and state the standard error.",
        "Use the Euclidean algorithm to find gcd(1,071, 462), then express the gcd as an integer combination of the two numbers.",
        "Write a Google Sheets formula that labels A2 as `late` only when its date precedes TODAY() and B2 is neither `done` nor blank; otherwise return an empty string.",
        "A parking lot contains cars and motorcycles: 38 vehicles and 126 wheels, assuming cars have four and motorcycles two. Find each count with equations.",
        "From a bag with five red, four blue, and three green tiles, three are sampled without replacement. Calculate the probability of exactly two red tiles.",
        "Factor `2x² - 7x - 15` over the integers and use the factors to solve the corresponding quadratic equation.",
        "A cone has radius 4 cm and slant height 9 cm. Find its lateral surface area and total surface area, exact and to two decimals.",
        "A canoe crosses a 600 m-wide river pointed perpendicular to shore at 2.4 m/s while current flows at 0.8 m/s. Find crossing time and downstream drift.",
        "The grouped counts for scores 0, 1, 2, 3, 4 are 2, 5, 8, 4, 1. Compute the weighted mean and population variance without expanding the list.",
        "Convert 68°F to Celsius and kelvin. Show formulas and round kelvin to two decimals.",
        "A loan of $6,000 uses simple interest at 5.5% for 18 months. Find interest and total repayment, distinguishing years from months.",
        "A model is drawn at 3:80 scale. A real doorway is 2.08 m tall. How tall should it be on the model in centimeters?",
        "A caterer expects 84 guests. Vegetarian meals are 3/7 of the total, vegan meals are one quarter of the vegetarian meals, and the rest are standard. Find all three counts.",
        "Find an equation perpendicular to `3x - 2y = 8` that passes through (6, 1). Give both point-slope and standard form.",
        "A subscription rises from $18 to $21.60, then later falls to $19.44. Compute the percentage increase and subsequent percentage decrease.",
        "Eight workers can label 4,800 jars in six hours. At the same individual rate, how many workers are required for 7,200 jars in five hours?",
        "A diagnostic test has 90% sensitivity and 95% specificity in a population with 2% prevalence. Out of 10,000 people, compute the expected true and false positives and the positive predictive value.",
        "Find all integers n from 1 through 100 that are divisible by 6 but not by 9. Give a counting argument rather than listing every value.",
        "A cell contains text like `AB-0042`. Give an Excel formula that extracts the numeric suffix as the number 42, while returning `NA()` if the hyphen is missing.",
    ],
    "science_technical": [
        "Explain how stomata balance carbon-dioxide uptake with water loss. Include guard cells and one environmental condition that tends to close stomata.",
        "A 0.25 kg ball moving at 12 m/s is stopped in 0.08 s. Calculate its change in momentum and average force, clearly stating the sign convention.",
        "Why does adding salt lower water's freezing point? Explain qualitatively using dissolved particles and chemical potential, without saying salt makes water intrinsically colder.",
        "Describe how P and S waves provide evidence for Earth's liquid outer core. Compare what each wave can travel through and the observed shadow zones.",
        "Explain why a star's spectrum contains dark absorption lines and what those lines can reveal. Distinguish composition from Doppler motion.",
        "Design an investigation of whether seed germination changes with soil salinity. Include treatment levels, random assignment, replication, and a criterion for germination.",
        "Water fills a rooftop tank to a depth of 3.2 m. Using density 1,000 kg/m³ and g = 9.8 m/s², calculate gauge pressure at the bottom and explain why tank width does not enter the result.",
        "Explain how vaccination can reduce disease transmission and why no vaccine needs to be 100% effective to have population-level benefits. Avoid promising individual outcomes.",
        "Compare El Niño with ordinary seasonal warming of coastal water. Mention changes to equatorial Pacific winds and why global weather effects can follow.",
        "Describe the energy conversions in regenerative braking for an electric vehicle. Explain why not all kinetic energy returns to the battery.",
        "A lake's surface warms rapidly while deeper water remains cold and oxygen-poor. Explain thermal stratification and how autumn turnover can alter oxygen distribution.",
        "A uniform 4 m beam weighing 600 N is hinged at one end and held horizontal by an upward cable at the other. Find the cable force and hinge's vertical reaction using torque and force balance.",
        "Explain CRISPR-Cas9 at a conceptual level using guide RNA, target DNA, Cas9, and cellular repair. Include one reason off-target changes matter.",
        "A paper-chromatography spot travels 4.8 cm while the solvent front travels 7.5 cm. Calculate its retention factor, explain why it has no units, and name one condition that must stay consistent across comparisons.",
        "Why does the Moon show phases while Earth experiences eclipses much less often? Use orbital geometry and inclination.",
        "Compare a fuse with a circuit breaker: how each interrupts excessive current, whether it can be reused, and why neither should be bypassed.",
        "Explain how enzymes change reaction rates without changing equilibrium. Use activation energy and active site accurately.",
        "A 9 V battery drives 0.30 A through a resistor. Compute resistance and power, then energy used over five minutes.",
        "Describe why soap helps remove oily dirt in water. Explain the hydrophilic head, hydrophobic tail, and micelle without claiming the oil chemically vanishes.",
        "Explain how a river meander migrates through erosion and deposition. Identify the outer and inner banks and relate flow speed to both.",
        "Compare redshift caused by cosmic expansion with everyday Doppler redshift. State the useful analogy and where it becomes incomplete.",
        "Propose a double-blind test of whether label color changes perceived sweetness when the drink itself is identical. Name a likely confound and the response scale.",
        "A copper wire has resistance 2.0 Ω at 20°C and temperature coefficient 0.0039/°C. Estimate resistance at 80°C using the linear approximation.",
        "Explain why viruses are not killed by antibiotics and why antiviral drugs are often virus-specific. Use replication machinery as part of the explanation.",
        "Describe the greenhouse effect from incoming sunlight through outgoing infrared radiation. Distinguish it from ozone depletion.",
        "Explain how a heat pump can deliver more thermal energy than the electrical energy it consumes without violating conservation of energy.",
        "A stream downstream from a mine has pH 3.4 and orange iron deposits. Describe acid mine drainage, one ecological effect, and one measurement needed before choosing remediation.",
        "Explain terminal velocity for a falling raindrop using gravity, drag, and net force. Clarify whether acceleration is zero before or after the forces balance.",
        "Describe how messenger RNA is translated into protein. Include ribosome, codon, transfer RNA, and stop codon, but do not imply one gene always yields one final protein.",
        "A balance gives readings 50.02, 50.01, 50.01 g for a certified 50.50 g mass. Diagnose accuracy and precision, then distinguish calibration from simply zeroing it.",
        "Explain why summer daylight lasts longer at high northern latitudes. Connect axial tilt, the Sun's apparent path, and what happens six months later.",
        "Compare electrical power transmission at high versus low voltage for the same delivered power. Use current and I²R losses and mention transformer roles.",
    ],
}


HELDOUT_TEST = {
    "business_operations": [
        "A repair company has 46 open jobs: 18 urgent, 20 standard, and 8 awaiting parts. Three technicians can each finish four jobs per day, but awaiting-parts jobs cannot start. Create a two-day allocation rule and identify the operational bottleneck.",
        "Draft a one-page outline for a postmortem after a warehouse shipped 73 orders with an outdated label. Separate timeline, impact, contributing conditions, containment, and corrective actions; use blameless language.",
        "Compare two suppliers for 1,000 cartons: Oriel charges $0.82 each with $140 freight and 2% historical defects; Vesta charges $0.91 with free freight and 0.5% defects. Calculate landed cost and state what additional cost is needed for a decision.",
        "A bakery's queue is longest from 7:40-8:20, while one employee spends 25 minutes restocking at 8:00. Propose a low-risk staffing experiment, the metric to watch, and a rollback condition.",
        "Turn these objectives into three measurable quarterly key results: improve support responsiveness, reduce preventable returns, and make inventory records more reliable. Avoid targets that merely count activity.",
        "Create a RACI-style assignment for launching a weekend pop-up with roles owner, operations lead, designer, and cashier. Cover permit, price list, signage, cash setup, and closing inventory, with exactly one accountable role per item.",
        "A subscription service begins the month with 2,400 customers, adds 180, loses 96, and upgrades 72 existing customers. Compute logo churn and ending customer count; explain why upgrades are not new logos.",
        "Write a concise escalation note about a vendor who missed two milestones but has not yet breached the final delivery date. Include evidence, business impact, requested recovery plan, and decision deadline without threatening litigation.",
        "Design a cycle-count schedule for 600 A-items counted monthly, 1,200 B-items quarterly, and 2,400 C-items annually across 50 working weeks. Give approximate weekly counts by class.",
        "A call center reports average handle time falling from 8.1 to 6.9 minutes while repeat calls rise from 9% to 17%. Explain why the first metric alone is misleading and propose a balanced scorecard.",
        "Provide acceptance criteria for a new returns portal: lookup by order and email, eligibility explanation, printable label, exchange option, and graceful behavior when the carrier service is unavailable.",
        "A small manufacturer can make 120 frames or 200 brackets per day on one machine. An order requires 360 frames and 600 brackets. Find the minimum machine-days and suggest a schedule with no fractional daily changeover.",
        "Write a five-question customer interview guide for learning why trial users abandon a scheduling app. Questions must be behavior-based, nonleading, and avoid asking users to design features.",
        "Map a simple incident-response handoff from store manager to regional operations when refrigeration temperature exceeds policy. Include immediate product isolation, timestamped evidence, ownership transfer, and closure confirmation.",
        "A project has tasks A (2 days), B after A (4), C after A (3), D after both B and C (2), and E after C (5). Find the critical path and project duration.",
        "Summarize a make-or-buy decision framework for a component that is strategically important but currently low volume. Include capacity, quality control, intellectual property, switching cost, and uncertainty rather than forcing a conclusion.",
    ],
    "finance_accounting_economics": [
        "A firm invoices $24,000 in December, collects $15,000, pays $7,000 of current expenses, and receives a $6,000 customer deposit for January work. Compare December cash-basis and accrual-basis revenue using only these facts.",
        "Prepare the journal entries when equipment costing $18,000 is purchased for $3,000 cash plus a $15,000 note. Then record one month of straight-line depreciation over five years with zero salvage value.",
        "A bond has $1,000 face value, 5% annual coupon paid yearly, and sells for $960. Compute current yield and explain why it is not the same as yield to maturity.",
        "Explain price elasticity of demand using a coffee shop that raises price 10% and observes quantity sold fall 15%. Calculate the simple percentage elasticity and interpret its magnitude without claiming causation.",
        "A retailer has beginning inventory $42,000, purchases $118,000, ending inventory $37,000, and sales $205,000. Compute cost of goods sold and gross margin dollars and percentage.",
        "Create a monthly cash forecast from opening cash $12,500, expected receipts $31,000, payroll $18,000, rent $4,200, supplier payments $16,500, and a required $8,000 minimum balance. Determine financing need.",
        "An index fund charges 0.08% annually and an active fund charges 0.85%. On $40,000 with identical pre-fee return, estimate the first-year fee difference and state why this alone does not predict future performance.",
        "Distinguish a sunk cost from an opportunity cost in deciding whether to attend the final session of a prepaid course instead of accepting a paid shift. Identify each relevant amount conceptually.",
        "A company reports net income $86,000, depreciation $14,000, accounts receivable increase $9,000, inventory decrease $5,000, and accounts payable decrease $3,000. Compute operating cash flow by the indirect method.",
        "Explain how a central bank policy-rate increase can affect borrowing, saving, aggregate demand, inflation, and exchange rates. Present it as possible transmission channels, not guaranteed outcomes.",
        "A freelancer earns $72,000 of revenue, has $19,000 deductible business expenses, and made $8,000 estimated payments. Calculate taxable business profit only; explicitly decline to infer total tax owed without jurisdiction and personal facts.",
        "Reconcile a bank statement balance of $9,840 with deposits in transit $1,250 and outstanding checks $930. The books show $10,115 before a $45 bank fee. Compute adjusted balances and identify any remaining discrepancy.",
        "Compare FIFO and weighted-average inventory costing during rising purchase prices. Explain expected direction of cost of goods sold and ending inventory without claiming either method is universally preferable.",
        "An economy's nominal GDP grows from $500B to $535B while the GDP deflator rises from 100 to 104. Estimate real growth and show the deflation calculation.",
        "A startup offers net-30 terms and has annual credit sales of $1.46M with average receivables $160,000. Compute days sales outstanding using 365 days and interpret cautiously.",
        "Explain diversification to someone considering putting all savings in their employer's stock. Cover correlated income risk, unsystematic risk, and why diversification does not eliminate market losses; avoid personalized investment instructions.",
    ],
    "legal_policy_compliance": [
        "Rewrite a website consent notice so it separately requests optional analytics cookies and necessary session cookies. Use plain language, avoid preselected consent, and state that withdrawing analytics consent does not end the session.",
        "A records policy lists invoices, job applications, security logs, and newsletter signups but gives every category a seven-year retention period. Identify the compliance-design problem and propose a jurisdiction-neutral review process rather than legal conclusions.",
        "Draft an internal checklist for responding to a data-subject access request: identity verification, scope clarification, system search, third-party review, secure delivery, and deadline tracking. Note that local law determines exact deadlines.",
        "A hiring manager wants to ask candidates whether they have children to predict schedule reliability. Explain the fairness and legal risk in general terms and suggest a job-related availability question.",
        "Summarize the difference between a policy, a standard, a procedure, and a guideline using password management as one consistent example.",
        "Create an accessible public-comment procedure for a city meeting with in-person, phone, and written options. Include equal time limits, accommodation requests, moderation rules, and publication of submitted comments.",
        "A vendor contract says only 'reasonable security.' List six concrete security schedule topics the parties should define, including incident notice and subcontractors, without drafting jurisdiction-specific clauses.",
        "Write a neutral incident acknowledgement to a customer after their personal information may have been exposed. Confirm investigation, provide a contact channel, avoid unsupported scope claims, and do not speculate about liability.",
        "Explain why deleting a file from the main application may not immediately remove it from backups. Propose policy language covering backup rotation, restore controls, and exceptional legal holds.",
        "A nonprofit wants volunteers to photograph children at an event. Build a risk checklist covering guardian permission, opt-out identification, location metadata, storage access, posting approval, and deletion requests.",
        "Compare anonymous reporting and confidential reporting in a workplace hotline. Explain benefits, investigation constraints, anti-retaliation messaging, and why anonymity cannot always be guaranteed by technology.",
        "Draft a conflict-of-interest disclosure form prompt for a grant-review panel. Ask about financial, professional, and close personal relationships, and provide recusal as an outcome without implying every disclosure is misconduct.",
        "A team proposes collecting birth date, precise location, contacts, and microphone access for a basic flashlight app. Apply data minimization and purpose limitation to each field.",
        "Outline a policy exception workflow with requester, business rationale, risk assessment, compensating controls, owner approval, expiration date, and periodic review. Make clear that silence is not approval.",
        "Explain at a high level why public-domain status, a permissive license, and fair use are different ways content might be reusable. Encourage checking jurisdiction and license terms rather than deciding a specific case.",
        "Turn a vague rule—'employees must use AI responsibly'—into five auditable control statements addressing confidential data, human review, source verification, prohibited decisions, and incident reporting.",
    ],
    "medicine_health": [
        "A patient-facing leaflet says a screening test can detect disease early but may produce false positives and false negatives. Rewrite it in plain language and include questions a patient could ask a clinician; do not recommend whether to test.",
        "Explain the difference between a viral upper-respiratory infection and a bacterial infection at a general educational level. Include why symptoms alone may not identify the cause and when urgent breathing difficulty warrants immediate care.",
        "Create a non-diagnostic symptom diary template for recurrent headaches. Include timing, duration, severity, associated symptoms, sleep, food, medication taken, and impact on activity while avoiding causal assumptions.",
        "An educational chart lists blood pressures 118/76, 142/91, and 134/84 on different days. Explain why one reading should not establish a diagnosis and describe accurate home-measurement technique generally.",
        "Summarize how sleep regularity, light exposure, caffeine timing, and naps can influence sleep. Separate low-risk sleep-hygiene ideas from a recommendation to seek professional evaluation for persistent impairment.",
        "A caregiver asks what dehydration can look like in an older adult. Give general warning signs, note that causes vary, and identify severe confusion or inability to keep fluids down as reasons for prompt medical help.",
        "Explain why a medicine can have both a generic name and a brand name. Include active ingredient, formulation differences, and the importance of checking with a pharmacist before assuming products are interchangeable.",
        "Draft a teach-back prompt a nurse could use after explaining wound-care instructions. It should avoid shaming, ask the patient to demonstrate understanding, and provide a route for clarification.",
        "Compare incidence and prevalence using a hypothetical town with 20 new cases this year and 75 total residents currently living with a condition. Do not calculate rates without the population size.",
        "Create a balanced educational explanation of vaccine side effects versus adverse events. Distinguish timing from causation and point to clinical or public-health sources for individual concerns.",
        "A fitness tracker reports unusually low sleep and elevated resting heart rate after travel. Explain why consumer-device readings can be noisy, suggest checking trends and device fit, and avoid diagnosing an illness.",
        "Write a food-allergy restaurant card template that names the allergen, asks about ingredients and cross-contact, and requests confirmation from kitchen staff. Do not promise that a kitchen can eliminate risk.",
        "Explain physical therapy's general role after an uncomplicated joint injury and why progression depends on assessment. Avoid supplying exercises or timelines for an unidentified injury.",
        "A public-health team sees vaccination coverage averaged across a county. Explain how the average can hide low-coverage neighborhoods and propose privacy-preserving ways to examine geographic disparities.",
        "Draft a concise message encouraging someone with sudden facial droop and speech difficulty to call emergency services immediately. Avoid lengthy background, diagnosis certainty, or advice to drive themselves.",
        "Explain why randomized controlled trials use comparison groups and random assignment. Mention placebo effects, confounding, adherence, and why trial results still may not apply identically to every person.",
    ],
    "cybersecurity_infrastructure": [
        "A service account suddenly downloads 40 GB at 02:00 from a repository it normally reads weekly. Create a defensive triage checklist covering identity, source host, authorization, logs, containment, and preservation of evidence.",
        "Explain the difference between encryption in transit, encryption at rest, and end-to-end encryption using a team-chat service. State what each protects and one threat it does not solve.",
        "Design a least-privilege role set for a deployment platform with developers, release managers, auditors, and emergency responders. Separate code submission, production approval, log reading, and break-glass access.",
        "A public API is seeing bursts from rotating addresses. Compare per-IP rate limits, account-level quotas, proof-of-work or challenges, and global circuit breakers, noting a fairness drawback of each.",
        "Write an incident-status update after a database failover caused 18 minutes of elevated errors. Include current status, user impact, mitigation, next update time, and uncertainty without naming a root cause prematurely.",
        "Explain how phishing-resistant authentication differs from SMS one-time codes. Mention origin binding, relay attacks, recovery procedures, and why no authentication method removes endpoint risk.",
        "Propose a backup restoration drill for a 2 TB document store. Define recovery point and recovery time objectives, isolated restore, integrity checks, sampled application tests, and evidence capture.",
        "A container image contains a high-severity library vulnerability, but the affected feature may be unreachable. Outline a risk assessment using exploitability, exposure, compensating controls, patch availability, and verification rather than severity alone.",
        "Compare blue-green and canary deployments for a stateful web service. Address rollback, database compatibility, observability, traffic control, and infrastructure cost.",
        "Create a log-redaction policy for authorization headers, session identifiers, email addresses, request bodies, and error traces. Balance debugging usefulness against secret and personal-data exposure.",
        "Explain split-horizon DNS and give one operational failure it can cause when internal and external records drift. Include a monitoring check.",
        "A TLS certificate expires in nine days. Provide an operational renewal runbook with ownership, validation method, staging verification, deployment, chain inspection, and post-change monitoring.",
        "Describe threat modeling for a file-upload endpoint using assets, trust boundaries, abuse cases, controls, and residual risk. Stay defensive and do not include executable exploit payloads.",
        "A queue consumer is processing duplicate messages after timeouts. Explain at-least-once delivery and propose idempotency keys, transactional boundaries, deduplication retention, and metrics.",
        "Write a safe communication to staff after a password manager outage. Tell them how to access approved recovery channels, warn against sharing secrets in chat, and avoid suggesting insecure temporary storage.",
        "Compare horizontal scaling with vertical scaling for an in-memory cache. Discuss sharding, hot keys, failover, cost, operational complexity, and consistency during rebalancing.",
    ],
    "humanities_social_sciences": [
        "Compare how a primary-source diary and a later textbook can contribute to studying a labor strike. Address proximity, perspective, selection, hindsight, and corroboration without treating either source as automatically truthful.",
        "Explain the difference between correlation and causation using an observed relationship between library visits and exam scores. Name at least two plausible confounders and one stronger study design.",
        "Analyze a fictional town monument debate through historical significance, present-day harm, public space, removal versus contextualization, and who participates in the decision. Do not endorse one outcome.",
        "Summarize the concept of opportunity structure in social movements with an invented example involving transit advocates. Distinguish resources from political openings.",
        "A translated poem uses the word 'home' four times where the source language distinguishes birthplace, household, homeland, and belonging. Explain the translator's tradeoff and propose an annotation strategy.",
        "Describe how an archaeologist might infer household food practices from animal bones, plant remains, cookware, and residue analysis. Include preservation bias and alternative explanations.",
        "Compare first-past-the-post and proportional representation on district representation, party proportionality, coalition incentives, and voter choice without ranking them universally.",
        "Explain survivorship bias using a historical archive that preserves letters from wealthy merchants more often than day laborers. Suggest three sources that could partially broaden the record.",
        "Analyze a fictional advertisement that depicts a spotless kitchen and says 'A good family starts here.' Discuss audience, gender norms, aspiration, omission, and historical context.",
        "Describe code-switching as a linguistic and social practice. Give two contexts in which speakers might shift varieties and avoid framing one variety as deficient.",
        "A poll about public transit is conducted only through a smartphone app. Identify coverage, self-selection, question-order, and nonresponse concerns, then suggest feasible mitigations.",
        "Explain the tragedy of the commons and one limitation of applying it mechanically to every shared resource. Use a community fishery with locally enforced rules as the example.",
        "Compare a memoir with oral-history interviews as evidence about migration. Discuss memory, narrative construction, interviewer effects, individual variation, and ethical consent.",
        "Define moral panic and distinguish it from justified public concern. Provide diagnostic questions for analyzing a fictional news cycle without declaring the concern unreal.",
        "Explain how maps exercise power through projection, boundaries, labels, scale, and omitted features. Use a hypothetical regional transit map rather than a geopolitical dispute.",
        "Construct a short argument both for and against returning a ceremonial object from a museum to its community of origin. Identify factual questions that would matter before a conclusion.",
    ],
    "creative_design_storytelling": [
        "Write a 180-word scene in which a lighthouse keeper realizes the foghorn is answering in a pattern. Keep the cause unresolved, include one concrete maintenance detail, and avoid describing the sea as angry.",
        "Invent a tabletop-game mechanic about restoring a wetland where players share flood risk but have private objectives. Explain setup, one turn, and how cooperation can fail without making sabotage optimal.",
        "Create three distinct visual directions for a neighborhood night-market poster. For each, specify palette, typography mood, imagery, and a readability risk; no images need to be generated.",
        "Write a dialogue between an old elevator and its newly installed voice assistant. Give each a different speaking rhythm and let the conflict concern memory rather than job replacement.",
        "Design a museum interactable that teaches visitors how braided rivers change channels. Include a physical action, feedback, accessibility alternative, reset mechanism, and one misleading inference to prevent.",
        "Outline a mystery whose apparent locked-room trick is actually a mistaken timestamp. Provide setup, three fair clues, the false assumption, and a nonviolent resolution.",
        "Compose a free-verse poem of 12-16 lines about repairing a winter coat. Use sound and texture, include no weather metaphors, and never use the words 'memory' or 'heart.'",
        "Create a character sketch for a meticulous street-tree inspector who secretly improvises jazz. Avoid making either trait a quirky contradiction; include a goal, pressure, blind spot, and habitual gesture.",
        "Propose a compact icon system for a trail map covering water, steep grade, viewpoint, shelter, and seasonal closure. Explain shared geometry and how meaning survives without color.",
        "Rewrite the premise 'a robot learns to love' into four less familiar speculative-fiction premises. Each must define what changes, what remains constrained, and the central ethical tension.",
        "Write an opening paragraph in second person about entering an abandoned greenhouse at noon. Create tension through ordinary physical details and do not use darkness, blood, whispers, or a sudden noise.",
        "Develop a three-course fictional menu inspired by geological processes. Make every dish plausible to serve, explain the visual analogy, and include one vegetarian main course.",
        "Storyboard a 30-second silent animation showing why an umbrella is passed among strangers. Use six shots, describe framing and action, and ensure the story reads without text labels.",
        "Invent five names for a typeface designed for small labels in botanical gardens. Avoid Latin plant names; choose one and describe its personality and functional features.",
        "Write a folktale synopsis in which a village bargains with its echo. Include a repeated rule, a clever communal solution, and a cost that prevents an effortless happy ending.",
        "Design a calm error state for an app that failed to save a long journal entry. Specify headline, body copy, actions, autosaved-data status, and what information should never be blamed on the user.",
    ],
    "multilingual_translation": [
        "Translate into natural Spanish for a community notice: 'The west entrance will be closed on Monday. Use the ramp beside the garden. Staff can help carry small items.' Then explain one register choice in English.",
        "Translate the French sentence `Je viens de fermer la fenêtre` into English and explain how `venir de` changes the time meaning. Give one contrasting translation of `Je viens fermer la fenêtre`.",
        "A Japanese learner writes `昨日、映画を見ますでした。` Correct the sentence for 'I watched a movie yesterday' and briefly explain the verb form without using romanization alone.",
        "Render 'Please leave the package with the front desk, not outside the door' in polite German suitable for a delivery note. Back-translate literally enough to show where the contrast appears.",
        "Explain to an English speaker why Spanish `embarazada` is a false friend. Give a safe example sentence and two natural Spanish options for expressing embarrassment.",
        "Translate this plain-language safety message into Brazilian Portuguese: 'If you smell gas, go outside and call the emergency number. Do not turn lights on or off.' Preserve the imperative urgency and add no steps.",
        "Compare the English terms 'privacy' and 'secrecy' for a translator working into a language that may use one broad term. Give contextual distinctions rather than inventing a target-language word.",
        "Translate `회의가 미뤄질 수도 있어요` from Korean into two English versions: one conversational and one formal. Explain how the source expresses uncertainty.",
        "An Arabic-to-English subtitle literally reads 'May your hands be safe' after someone finishes cooking. Suggest a contextually natural English subtitle and explain why word-for-word translation may mislead.",
        "Rewrite this machine-like English into natural customer support language without changing facts: 'Your request under processing is. Completion expected within two business days.' Then translate the revision into simple Italian.",
        "Explain the ambiguity in Chinese `他没告诉我经理来了` by giving two punctuated or paraphrased readings in English. Do not claim tone alone always resolves it.",
        "Translate into Canadian French for a public sign: 'Quiet room available on the second floor. Ask at reception for the access code.' Keep it concise and explain the choice for 'reception.'",
        "A translator must adapt 'bring a dish to pass' for an international event invitation. Provide clear English that avoids the regional idiom, then versions in Spanish and French.",
        "Correct the English learner sentence 'I am living here since three years' in both American English and a natural present-perfect construction. Explain duration with `for` versus starting point with `since`.",
        "Translate the Hindi sentence `काम धीरे हुआ, लेकिन ठीक हुआ` into idiomatic English in two tones: neutral report and encouraging remark. Explain how the second tone is an adaptation.",
        "Create a bilingual English-Spanish label for a museum button that starts and stops an audio description. Use very short parallel phrases, then note a potential ambiguity if only `play` is translated literally.",
    ],
}
