#!/usr/bin/env python3
"""Run independent Codex quality review over completed local generations.

This is deliberately separate from generation and selection.  It never edits
assistant outputs; it only labels whether a complete model-generated
conversation is suitable for the high-quality candidate pool.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

try:
    from .generate_responses import (GENERATED, RAW,
                                     build_generation_validation_context,
                                     read_jsonl, validate_generated_record,
                                     versioned_directory)
    from .pipeline_contract import require_current_reference_audit
except ImportError:  # Direct script execution.
    from generate_responses import (GENERATED, RAW,
                                    build_generation_validation_context,
                                    read_jsonl, validate_generated_record,
                                    versioned_directory)
    from pipeline_contract import require_current_reference_audit


ROOT = Path(__file__).resolve().parent
SCHEMA = ROOT / "judge_schema.json"
JUDGE_ROOT = GENERATED / "judge"

RUBRIC = """You are independently quality-reviewing synthetic SFT conversations.
Every assistant turn was generated by the small model named in the payload.
Evaluate the entire conversation, including a follow-up when present.

Set each of the seven named boolean gates independently. Accept only if the
assistant response passes every gate:
1. `semantic_correct`: checkable facts, arithmetic, code, translation, and
   causal claims are substantively correct;
2. `instruction_compliant`: the actual request and all material constraints
   are followed;
3. `safe`: the response preserves required safety boundaries;
4. `format_compliant`: required output structure and formatting are followed;
5. `complete`: no material answer, revision, or placeholder is unresolved;
6. `no_truncation`: the response ends naturally and is not cut off;
7. `no_repetition`: there is no pathological repeated content.

Reject confident errors, missed core instructions, malformed requested formats,
uncompilable central code, broken calculations, unsafe advice, truncation, generic
answers that evade the specifics, and multi-turn answers that fail to perform the
requested revision. A score of 4 or 5 must map to accept and all seven gates
true; 1-3 or any false gate must map to reject. Use short, concrete reason
labels. Return one review for every candidate exactly
once, in input order. When a private `quality_reference` is supplied, use its
answer key and required facts to check the generated answer; never judge mere
word-for-word similarity. Do not use tools or external sources; the supplied
tasks and references are self-contained.
"""
RUBRIC_VERSION = 2
JUDGE_BATCH_SIZE = 24

QUALITY_GATES = frozenset({
    "semantic_correct", "instruction_compliant", "safe",
    "format_compliant", "complete", "no_truncation", "no_repetition",
})


def canonical_sha256(value) -> str:
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True,
                         separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate_raw_reviews(reviews: object, expected_ids: list[str]) -> list[dict]:
    """Apply the complete judge schema and score/gate semantics on every load."""
    if not isinstance(reviews, list) or len(reviews) != len(expected_ids):
        raise RuntimeError("judge reviews have the wrong length")
    if [row.get("candidate_id") for row in reviews
            if isinstance(row, dict)] != expected_ids:
        raise RuntimeError("judge review IDs are missing, duplicated, or reordered")
    required_keys = {"candidate_id", "verdict", "score", "gates", "reasons"}
    for review in reviews:
        if not isinstance(review, dict) or set(review) != required_keys:
            raise RuntimeError("judge review does not match the closed schema")
        gates = review.get("gates")
        reasons = review.get("reasons")
        if (review.get("verdict") not in {"accept", "reject"} or
                type(review.get("score")) is not int or
                not 1 <= review["score"] <= 5 or
                not isinstance(gates, dict) or set(gates) != QUALITY_GATES or
                any(type(value) is not bool for value in gates.values()) or
                not isinstance(reasons, list) or len(reasons) > 4 or
                any(not isinstance(reason, str) or not reason.strip()
                    for reason in reasons)):
            raise RuntimeError(
                f"judge review schema is invalid for {review.get('candidate_id')}")
        expected_verdict = (
            "accept" if review["score"] >= 4 and all(gates.values())
            else "reject")
        if review["verdict"] != expected_verdict:
            raise RuntimeError(
                f"judge verdict/score/gates disagree for {review['candidate_id']}")
    return reviews


def validate_judge_batch_payload(
        output: Path, raw_output: Path, log: Path, rows: list[dict],
        judge_model: str, reasoning: str, codex_version: str,
        manifest_version: int) -> dict:
    """Authenticate normalized reviews against preserved raw Codex output."""
    provenance = expected_provenance(
        rows, judge_model, reasoning, codex_version, manifest_version)
    try:
        payload = json.loads(output.read_text())
        raw_payload = json.loads(raw_output.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError("judge batch proof files are missing or invalid") from exc
    expected_ids = [row["candidate_id"] for row in rows]
    raw_reviews = validate_raw_reviews(raw_payload.get("reviews"), expected_ids)
    if set(raw_payload) != {"reviews"}:
        raise RuntimeError("raw judge output violates its closed top-level schema")
    if (payload.get("provenance") != provenance or
            payload.get("model_output_sha256") != file_sha256(raw_output) or
            not log.is_file() or
            payload.get("invocation_log_sha256") != file_sha256(log)):
        raise RuntimeError("judge batch content/log provenance is invalid")
    normalized = []
    for review, source in zip(raw_reviews, provenance["sources"]):
        normalized.append({
            **review,
            "conversation_sha256": source["conversation_sha256"],
            "quality_reference_sha256": source[
                "quality_reference_sha256"],
            "generation_input_sha256": source["generation_input_sha256"],
            "manifest_row_sha256": source["manifest_row_sha256"],
        })
    if payload.get("reviews") != normalized:
        raise RuntimeError("normalized judge reviews differ from raw model output")
    return payload


def conversation_sha256(row: dict) -> str:
    return canonical_sha256({
        "candidate_id": row["candidate_id"],
        "model_id": row["model_id"],
        "messages": row["messages"],
    })


def expected_provenance(rows: list[dict], judge_model: str, reasoning: str,
                        codex_version: str, manifest_version: int) -> dict:
    sources = [{
        "candidate_id": row["candidate_id"],
        "conversation_sha256": conversation_sha256(row),
        "generation_backend": row.get("generation_backend"),
        "quality_reference_sha256": row.get(
            "_quality_reference", {}).get("reference_sha256"),
        "generation_input_sha256": row.get(
            "provenance", {}).get("generation_input_sha256"),
        "manifest_row_sha256": row.get(
            "provenance", {}).get("manifest_row_sha256"),
    } for row in rows]
    identity = {
        "judge_model": judge_model,
        "reasoning": reasoning,
        "configured_batch_size": JUDGE_BATCH_SIZE,
        "codex_version": codex_version,
        "rubric_version": RUBRIC_VERSION,
        "manifest_version": manifest_version,
        "rubric_sha256": hashlib.sha256(RUBRIC.encode()).hexdigest(),
        "schema_sha256": hashlib.sha256(SCHEMA.read_bytes()).hexdigest(),
        "judge_script_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "sources": sources,
    }
    return {**identity, "batch_sha256": canonical_sha256(identity)}


def require_complete_generation_matrix(
        model: str, rows: dict[str, dict], expected_ids: set[str]) -> None:
    if set(rows) != expected_ids:
        missing = sorted(expected_ids - set(rows))
        extra = sorted(set(rows) - expected_ids)
        raise RuntimeError(
            f"{model} raw generation matrix is incomplete: "
            f"expected={len(expected_ids)}, actual={len(rows)}, "
            f"missing={missing[:8]}, extra={extra[:8]}")


def latest(model: str, manifest_version: int,
           audit_proof: dict | None = None) -> list[dict]:
    if manifest_version != 2 or audit_proof is None:
        raise RuntimeError("semantic judging requires the current audited v2 sources")
    try:
        import transformers
    except ImportError as exc:
        raise RuntimeError("transformers is required for generation validation") from exc
    context = build_generation_validation_context(
        transformers, audit_proof, model)
    allowed = context["manifest_by_id"]
    rows = {}
    raw_root = versioned_directory(RAW, manifest_version)
    for row in read_jsonl(raw_root / f"{model}.jsonl"):
        candidate_id = row.get("candidate_id")
        if not isinstance(candidate_id, str) or not candidate_id:
            raise RuntimeError(f"{model} raw generation has an invalid ID")
        rows[candidate_id] = row
    expected_ids = set(allowed)
    require_complete_generation_matrix(model, rows, expected_ids)
    for candidate_id in sorted(rows):
        validate_generated_record(rows[candidate_id], context)
    # Grossly truncated or over-limit generations already have deterministic
    # rejection reasons and do not consume independent-judge capacity.
    return [rows[key] for key in sorted(rows)
            if rows[key]["quality"]["accepted"]]


def payload_row(row: dict) -> dict:
    return {
        "candidate_id": row["candidate_id"],
        "model": row["model_id"],
        "surface_quality": row["quality"],
        "messages": row["messages"],
        "quality_reference": row.get("_quality_reference"),
    }


def run_batch(model: str, batch_index: int, rows: list[dict], judge_model: str,
              reasoning: str, codex_version: str,
              manifest_version: int, force: bool) -> tuple[int, str]:
    judge_root = versioned_directory(JUDGE_ROOT, manifest_version)
    directory = judge_root / model
    directory.mkdir(parents=True, exist_ok=True)
    output = directory / f"batch_{batch_index:03d}.json"
    raw_output = directory / f"batch_{batch_index:03d}.raw.json"
    log = directory / f"batch_{batch_index:03d}.log"
    ids = [row["candidate_id"] for row in rows]
    provenance = expected_provenance(
        rows, judge_model, reasoning, codex_version, manifest_version)
    if output.exists() and not force:
        try:
            validate_judge_batch_payload(
                output, raw_output, log, rows, judge_model, reasoning,
                codex_version, manifest_version)
            return batch_index, "cached"
        except RuntimeError:
            pass
    prompt = RUBRIC + "\nINPUT CONVERSATIONS:\n" + json.dumps(
        [payload_row(row) for row in rows], ensure_ascii=False)
    command = [
        "codex", "exec", "-m", judge_model,
        "-c", f'model_reasoning_effort="{reasoning}"',
        "--sandbox", "read-only", "--ephemeral",
        "--output-schema", str(SCHEMA),
        "--output-last-message", str(output), "-",
    ]
    completed = subprocess.run(
        command, input=prompt, text=True, stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT, cwd=ROOT, check=False)
    log.write_text(completed.stdout)
    if completed.returncode:
        raise RuntimeError(
            f"judge batch {model}/{batch_index} exited {completed.returncode}; "
            f"see {log}")
    raw_bytes = output.read_bytes()
    raw_output.write_bytes(raw_bytes)
    raw_payload = json.loads(raw_bytes)
    reviews = validate_raw_reviews(raw_payload.get("reviews"), ids)
    normalized = []
    for review, source in zip(reviews, provenance["sources"]):
        normalized.append({
            **review,
            "conversation_sha256": source["conversation_sha256"],
            "quality_reference_sha256": source[
                "quality_reference_sha256"],
            "generation_input_sha256": source[
                "generation_input_sha256"],
            "manifest_row_sha256": source["manifest_row_sha256"],
        })
    payload = {
        "reviews": normalized,
        "provenance": provenance,
        "model_output_sha256": file_sha256(raw_output),
        "invocation_log_sha256": file_sha256(log),
    }
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    validate_judge_batch_payload(
        output, raw_output, log, rows, judge_model, reasoning,
        codex_version, manifest_version)
    return batch_index, "completed"


def aggregate(model: str, rows: list[dict], batch_size: int,
              judge_model: str, reasoning: str, codex_version: str,
              manifest_version: int) -> dict:
    if batch_size != JUDGE_BATCH_SIZE:
        raise RuntimeError(
            f"semantic judge batch size is fixed at {JUDGE_BATCH_SIZE}")
    output_rows = []
    batch_provenance = []
    batch_payload_hashes = []
    raw_output_hashes = []
    invocation_log_hashes = []
    judge_root = versioned_directory(JUDGE_ROOT, manifest_version)
    directory = judge_root / model
    for index in range((len(rows) + batch_size - 1) // batch_size):
        path = directory / f"batch_{index:03d}.json"
        raw_path = directory / f"batch_{index:03d}.raw.json"
        log_path = directory / f"batch_{index:03d}.log"
        batch_rows = rows[index * batch_size:(index + 1) * batch_size]
        payload = validate_judge_batch_payload(
            path, raw_path, log_path, batch_rows, judge_model, reasoning,
            codex_version, manifest_version)
        batch_provenance.append(payload["provenance"])
        batch_payload_hashes.append(file_sha256(path))
        raw_output_hashes.append(payload["model_output_sha256"])
        invocation_log_hashes.append(payload["invocation_log_sha256"])
        output_rows.extend(payload["reviews"])
    expected = [row["candidate_id"] for row in rows]
    actual = [row["candidate_id"] for row in output_rows]
    if actual != expected:
        raise RuntimeError("aggregated judge output does not match source ordering")
    expected_hashes = [conversation_sha256(row) for row in rows]
    actual_hashes = [row.get("conversation_sha256") for row in output_rows]
    if actual_hashes != expected_hashes:
        raise RuntimeError("aggregated judge conversation hashes do not match source")
    result = {
        "model": model,
        "manifest_version": manifest_version,
        "judge_model": judge_model,
        "reasoning": reasoning,
        "batch_size": batch_size,
        "codex_version": codex_version,
        "rubric_version": RUBRIC_VERSION,
        "rubric_sha256": hashlib.sha256(RUBRIC.encode()).hexdigest(),
        "schema_sha256": hashlib.sha256(SCHEMA.read_bytes()).hexdigest(),
        "judge_script_sha256": hashlib.sha256(
            Path(__file__).read_bytes()).hexdigest(),
        "batch_sha256": [item["batch_sha256"] for item in batch_provenance],
        "batch_payload_sha256": batch_payload_hashes,
        "model_output_sha256": raw_output_hashes,
        "invocation_log_sha256": invocation_log_hashes,
        "sources_sha256": canonical_sha256([
            source for item in batch_provenance for source in item["sources"]]),
        "reviews": output_rows,
        "accepted": sum(row["verdict"] == "accept" for row in output_rows),
        "rejected": sum(row["verdict"] == "reject" for row in output_rows),
    }
    judge_root.mkdir(parents=True, exist_ok=True)
    (judge_root / f"{model}.json").write_text(
        json.dumps(result, indent=2, ensure_ascii=False) + "\n")
    return result


def load_validated_judge_aggregate(
        model: str, source_rows: list[dict]) -> tuple[dict[str, dict], dict]:
    """Reauthenticate an aggregate, every normalized batch, raw output, and log."""
    judge_root = versioned_directory(JUDGE_ROOT, 2)
    path = judge_root / f"{model}.json"
    try:
        result = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"missing judge aggregate for {model}") from exc
    batch_size = result.get("batch_size")
    if (result.get("model") != model or
            result.get("manifest_version") != 2 or
            result.get("judge_model") != "gpt-5.6-sol" or
            result.get("reasoning") != "high" or
            batch_size != JUDGE_BATCH_SIZE or
            result.get("rubric_version") != RUBRIC_VERSION or
            result.get("rubric_sha256") != hashlib.sha256(RUBRIC.encode()).hexdigest() or
            result.get("schema_sha256") != hashlib.sha256(SCHEMA.read_bytes()).hexdigest() or
            result.get("judge_script_sha256") != hashlib.sha256(
                Path(__file__).read_bytes()).hexdigest()):
        raise RuntimeError(f"stale judge aggregate for {model}")
    batch_count = (len(source_rows) + batch_size - 1) // batch_size
    fields = ("batch_sha256", "batch_payload_sha256",
              "model_output_sha256", "invocation_log_sha256")
    if any(not isinstance(result.get(field), list) or
           len(result[field]) != batch_count for field in fields):
        raise RuntimeError(f"judge aggregate proof vectors are invalid for {model}")
    directory = judge_root / model
    reviews = []
    provenances = []
    payload_hashes = []
    raw_hashes = []
    log_hashes = []
    for index in range(batch_count):
        batch_rows = source_rows[index * batch_size:(index + 1) * batch_size]
        output = directory / f"batch_{index:03d}.json"
        raw_output = directory / f"batch_{index:03d}.raw.json"
        log = directory / f"batch_{index:03d}.log"
        payload = validate_judge_batch_payload(
            output, raw_output, log, batch_rows, result["judge_model"],
            result["reasoning"], result.get("codex_version"), 2)
        reviews.extend(payload["reviews"])
        provenances.append(payload["provenance"])
        payload_hashes.append(file_sha256(output))
        raw_hashes.append(payload["model_output_sha256"])
        log_hashes.append(payload["invocation_log_sha256"])
    expected_ids = [row["candidate_id"] for row in source_rows]
    if ([row.get("candidate_id") for row in reviews] != expected_ids or
            result.get("reviews") != reviews or
            result.get("batch_sha256") != [
                item["batch_sha256"] for item in provenances] or
            result.get("batch_payload_sha256") != payload_hashes or
            result.get("model_output_sha256") != raw_hashes or
            result.get("invocation_log_sha256") != log_hashes):
        raise RuntimeError(f"judge aggregate differs from its batch proofs for {model}")
    expected_sources = [source for item in provenances
                        for source in item["sources"]]
    if (result.get("sources_sha256") != canonical_sha256(expected_sources) or
            result.get("accepted") != sum(
                row["verdict"] == "accept" for row in reviews) or
            result.get("rejected") != sum(
                row["verdict"] == "reject" for row in reviews)):
        raise RuntimeError(f"judge aggregate counts/sources are invalid for {model}")
    return {row["candidate_id"]: row for row in reviews}, result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", required=True,
                        choices=("qwen25", "qwen3", "qwen35"))
    parser.add_argument("--judge-model", default="gpt-5.6-sol")
    parser.add_argument("--reasoning", default="high",
                        choices=("low", "medium", "high"))
    parser.add_argument("--batch-size", type=int, default=JUDGE_BATCH_SIZE)
    parser.add_argument("--workers", type=int, default=2)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--manifest-version", type=int, default=1)
    args = parser.parse_args()
    if args.batch_size != JUDGE_BATCH_SIZE or args.workers < 1:
        raise SystemExit(
            f"judge batch size is fixed at {JUDGE_BATCH_SIZE}; workers must "
            "be positive")
    if (args.manifest_version != 2 or args.judge_model != "gpt-5.6-sol" or
            args.reasoning != "high"):
        raise SystemExit(
            "SLM v2 quality review requires manifest v2 and gpt-5.6-sol/high")
    contract = require_current_reference_audit(
        GENERATED / "prompt_candidates_v2.jsonl")
    rows = latest(args.model, args.manifest_version, contract)
    if not rows:
        raise SystemExit(f"no raw generations exist for {args.model}")
    batches = [rows[i:i + args.batch_size]
               for i in range(0, len(rows), args.batch_size)]
    codex_version = subprocess.check_output(
        ["codex", "--version"], text=True).strip()
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = {
            pool.submit(run_batch, args.model, index, batch,
                        args.judge_model, args.reasoning, codex_version,
                        args.manifest_version, args.force): index
            for index, batch in enumerate(batches)
        }
        for future in as_completed(futures):
            index, status = future.result()
            print(json.dumps({"batch": index, "status": status}), flush=True)
    result = aggregate(args.model, rows, args.batch_size, args.judge_model,
                       args.reasoning, codex_version, args.manifest_version)
    print(json.dumps({key: value for key, value in result.items()
                      if key != "reviews"}, indent=2))


if __name__ == "__main__":
    main()
